// Using realistic generic mock data

export const MOCK_AUDIT_LOGS = [
    {
        _id: "log_001",
        userId: { _id: "user_a", name: "Alice Admin", email: "alice@example.com" },
        userRole: "admin",
        action: "LOGIN_SUCCESS",
        resourceType: "auth",
        resourceId: null,
        description: "User logged in successfully.",
        ipAddress: "192.168.1.10",
        userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
        status: "success",
        createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    },
    {
        _id: "log_002",
        userId: { _id: "user_b", name: "Bob Manager", email: "bob@example.com" },
        userRole: "manager",
        action: "CREATE_PROJECT",
        resourceType: "project",
        resourceId: "proj_99",
        description: "Created project 'Q4 Marketing Campaign'.",
        ipAddress: "10.0.0.5",
        userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
        status: "success",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    },
    {
        _id: "log_003",
        userId: null,
        userRole: "unknown",
        action: "LOGIN_FAILED",
        resourceType: "auth",
        resourceId: null,
        description: "Auth Failure on /api/login. Attempted email: unknown@hacker.com",
        ipAddress: "203.0.113.42",
        userAgent: "curl/7.81.0",
        status: "failure",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    },
    {
        _id: "log_004",
        userId: { _id: "user_a", name: "Alice Admin", email: "alice@example.com" },
        userRole: "admin",
        action: "UPDATE_USER_ROLE",
        resourceType: "user",
        resourceId: "user_c",
        description: "Changed user 'Charlie' role from 'member' to 'manager'.",
        ipAddress: "192.168.1.10",
        userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
        status: "success",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    },
    {
        _id: "log_005",
        userId: { _id: "user_c", name: "Charlie Member", email: "charlie@example.com" },
        userRole: "member",
        action: "DELETE_TASK",
        resourceType: "task",
        resourceId: "task_123",
        description: "Attempted to delete task 'Setup DB' but failed.",
        ipAddress: "172.16.254.1",
        userAgent: "Mozilla/5.0 (X11; Linux x86_64)",
        status: "failure",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    },
    // Add some padding to test pagination
    ...Array.from({ length: 15 }).map((_, i) => ({
        _id: `log_gen_${i}`,
        userId: { _id: "user_a", name: "System Automation", email: "sys@example.com" },
        userRole: "system",
        action: i % 3 === 0 ? "SYNC_DATA" : "UPDATE_PROJECT",
        resourceType: i % 3 === 0 ? "system" : "project",
        resourceId: `proj_${i}`,
        description: `Automated background process ${i}`,
        ipAddress: "127.0.0.1",
        userAgent: "Node.js Scheduler",
        status: i === 7 ? "failure" : "success",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * (i + 50)).toISOString(),
    })),
];
